### PR TITLE
[Authorization] Handle unauthorized requests

### PR DESCRIPTION
**Pull request by marchi-martius**

### CODE REVIEW

**Comment by obliviusm** [comment]
@marchi-martius LGTM 
but i don't want to push to `master` until at least basic authorization is available. Because it will complicate development. 
Other option is to make some backdoor for development. so we could skip authorization check.
what do you think?

**Comment by marchi-martius** [comment]
@obliviusm I think we should implement basic authentication first.

**Comment by obliviusm** [comment]
@marchi-martius yeah, right. we also need authentication. so let's make authentication and authorization in separate branch and then merge them into master. At least, vert minimal working thing.

**Comment by marchi-martius** [comment]
What do you mean for authorization? Firebase rules?

**Comment by obliviusm** [comment]
No. I mean just to unite your authorization with basic authentication

**Comment by obliviusm** [comment]
@marchi-martius oh, I just got it. We can turn off firebase rules if needed . so authorization don't make any problems till we make authentication.
So it can be merged into master.
Sorry for my slow-thinking :)

Okay, let me re-check PR

**Review by obliviusm — APPROVED** [review]

**Pull request merged**
